"""
Leak & Overflow Detection LSTM (PyTorch).

Architecture:
    LSTM(input_dim -> hidden, num_layers=2) -> dropout -> linear(hidden -> 1)
    sigmoid output = anomaly probability per timestep within the window.

Training data is synthetic — generated by `_synthesize_dataset` — so the model
can be retrained end-to-end on first startup with no external dataset. The
synthetic generator includes leak/burst/overflow events so the validation
precision target (>= 0.7) can be met.

Public API:
    get_leak_lstm() -> LeakLSTMService
        .ready                  -> bool (model loaded)
        .meta                   -> dict (window_size, training_samples, etc.)
        .score_window(window)   -> probability in [0, 1]
        .train_if_missing(path) -> trains synthetic model when weights absent
"""
from __future__ import annotations

import json
import math
import random
import time
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np

try:
    import torch
    from torch import nn
    from torch.utils.data import DataLoader, TensorDataset
    HAS_TORCH = True
except ImportError:                                       # pragma: no cover
    HAS_TORCH = False


FEATURES = ["pressure_kpa", "flow_rate_lps", "acoustic_signal_db", "soil_moisture_pct"]
DEFAULT_WINDOW = 12
HIDDEN = 32
NUM_LAYERS = 2
DROPOUT = 0.15

MODEL_VERSION = "leak-lstm-v1.0"

WEIGHTS_PATH = Path("app/ml/weights/leak_lstm.pt")
META_PATH    = Path("app/ml/weights/leak_lstm_meta.json")


# ── Model ────────────────────────────────────────────────────────────────

if HAS_TORCH:

    class LeakLSTM(nn.Module):
        def __init__(self, n_features: int = len(FEATURES), hidden: int = HIDDEN,
                     num_layers: int = NUM_LAYERS, dropout: float = DROPOUT):
            super().__init__()
            self.lstm = nn.LSTM(
                n_features, hidden,
                num_layers=num_layers,
                batch_first=True,
                dropout=dropout if num_layers > 1 else 0.0,
            )
            self.head = nn.Sequential(
                nn.Linear(hidden, hidden // 2),
                nn.ReLU(),
                nn.Dropout(dropout),
                nn.Linear(hidden // 2, 1),
            )

        def forward(self, x: "torch.Tensor") -> "torch.Tensor":
            out, _ = self.lstm(x)              # (B, T, hidden)
            logits = self.head(out[:, -1, :])  # take last timestep
            return logits.squeeze(-1)          # (B,)


# ── Synthetic dataset ────────────────────────────────────────────────────

def _baseline_sample(rng: random.Random, noise: float = 0.05) -> Dict[str, float]:
    """Healthy sensor sample."""
    return {
        "pressure_kpa":       rng.gauss(420, 20 + 30 * noise),     # ~ 4.2 bar
        "flow_rate_lps":      max(0.0, rng.gauss(5.0, 0.5 + 1.0 * noise)),
        "acoustic_signal_db": rng.gauss(38.0, 1.5 + 2.0 * noise),  # background noise
        "soil_moisture_pct":  rng.gauss(28.0, 1.5 + 2.0 * noise),  # mid-range moist soil
    }


def _scenario_step(scenario: str, t: int, length: int, base: Dict[str, float]) -> Tuple[Dict[str, float], bool]:
    """Apply scenario-specific perturbations to a baseline sample."""
    s = dict(base)
    truth = False

    if scenario == "slow_leak":
        # gradual pressure drop + small flow rise + acoustic uptick after t/3
        if t > length / 3:
            progress = (t - length / 3) / max(1, length - length / 3)
            s["pressure_kpa"]       -= 50 * progress
            s["flow_rate_lps"]      += 2.5 * progress
            s["acoustic_signal_db"] += 8.0 * progress
            s["soil_moisture_pct"]  += 12.0 * progress
            truth = progress > 0.15

    elif scenario == "burst_pipe":
        # sharp pressure plunge + flow spike at burst_t
        burst_t = int(length * 0.55)
        if burst_t <= t < burst_t + max(2, length // 10):
            s["pressure_kpa"]       -= 200
            s["flow_rate_lps"]      += 12
            s["acoustic_signal_db"] += 25
            s["soil_moisture_pct"]  += 25
            truth = True
        elif t > burst_t + length // 10:
            # sustained low pressure + high flow as the burst continues
            s["pressure_kpa"]       -= 80
            s["flow_rate_lps"]      += 5
            s["acoustic_signal_db"] += 10
            truth = True

    elif scenario == "overflow":
        # flow exceeds capacity, pressure rises briefly, then plateaus
        if t > length / 2:
            progress = (t - length / 2) / max(1, length - length / 2)
            s["flow_rate_lps"]      += 8 * progress
            s["pressure_kpa"]       += 40 * (1 - abs(0.5 - progress))
            s["soil_moisture_pct"]  += 8 * progress
            truth = progress > 0.2

    elif scenario == "intermittent_leak":
        # leaks on/off in cycles
        period = max(8, length // 4)
        in_leak = (t % period) >= period * 0.6
        if in_leak and t > length / 5:
            s["pressure_kpa"]       -= 35
            s["flow_rate_lps"]      += 2
            s["acoustic_signal_db"] += 6
            truth = True

    # 'normal' or 'random' pass through baseline
    return s, truth


def _synthesize_dataset(
    n_sequences_per_scenario: int = 80, length: int = 60,
    window: int = DEFAULT_WINDOW, seed: int = 7,
) -> Tuple[np.ndarray, np.ndarray]:
    """Build (X_windows, y_anomaly) arrays from synthetic sequences."""
    rng = random.Random(seed)
    scenarios = ["normal", "slow_leak", "burst_pipe", "overflow", "intermittent_leak"]

    X_seqs: List[np.ndarray] = []
    y_seqs: List[np.ndarray] = []

    for scenario in scenarios:
        for _ in range(n_sequences_per_scenario):
            samples = []
            truths  = []
            base = _baseline_sample(rng, noise=rng.uniform(0.03, 0.15))
            for t in range(length):
                jitter = _baseline_sample(rng, noise=0.02)
                # use scenario-modified jitter for per-timestep variability
                drift, truth = _scenario_step(scenario, t, length, jitter)
                samples.append([drift[f] for f in FEATURES])
                truths.append(int(truth))
            X_seqs.append(np.asarray(samples, dtype=np.float32))
            y_seqs.append(np.asarray(truths, dtype=np.int8))

    # slide windows; label = "any anomaly in last 3 of window" (so we learn
    # to react with low latency rather than after the whole window)
    Xw, yw = [], []
    for X, y in zip(X_seqs, y_seqs):
        for i in range(len(X) - window + 1):
            Xw.append(X[i:i + window])
            tail = y[i + window - 3 : i + window]
            yw.append(int(tail.max()))
    return np.stack(Xw), np.asarray(yw, dtype=np.float32)


def _fit_scaler(X: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    flat = X.reshape(-1, X.shape[-1])
    mean = flat.mean(axis=0).astype(np.float32)
    std  = (flat.std(axis=0) + 1e-6).astype(np.float32)
    return mean, std


def _scale(X: np.ndarray, mean: np.ndarray, std: np.ndarray) -> np.ndarray:
    return (X - mean) / std


def _pick_threshold(probs: np.ndarray, y: np.ndarray, target_precision: float = 0.7) -> Tuple[float, float]:
    """Return (threshold, achieved_precision) — smallest threshold meeting target."""
    best_thr = 0.5
    best_prec = 0.0
    for thr in np.linspace(0.10, 0.95, 86):
        pred = (probs >= thr).astype(int)
        tp = int(((pred == 1) & (y == 1)).sum())
        fp = int(((pred == 1) & (y == 0)).sum())
        if tp + fp == 0:
            continue
        prec = tp / (tp + fp)
        if prec >= target_precision:
            return float(thr), float(prec)
        if prec > best_prec:
            best_thr, best_prec = float(thr), float(prec)
    return best_thr, best_prec


# ── Service singleton ───────────────────────────────────────────────────

@dataclass
class LeakLSTMService:
    window_size: int = DEFAULT_WINDOW
    features: List[str] = field(default_factory=lambda: list(FEATURES))
    model_version: str = MODEL_VERSION
    threshold: float = 0.5
    mean: Optional[np.ndarray] = None
    std: Optional[np.ndarray] = None
    last_retrained: Optional[str] = None
    training_samples: int = 0
    validation_precision: float = 0.0
    ready: bool = False
    _model: object = None  # torch.nn.Module

    # Per-sensor rolling buffer for live inference.
    _buffers: Dict[str, List[List[float]]] = field(default_factory=dict)

    # ────────────────────────────────────────────────────────────────────
    @property
    def meta(self) -> dict:
        return {
            "model_loaded": self.ready,
            "model_version": self.model_version,
            "window_size": self.window_size,
            "features": list(self.features),
            "last_retrained": self.last_retrained,
            "training_samples": self.training_samples,
            "validation_precision": round(self.validation_precision, 4),
        }

    # ── Persistence ─────────────────────────────────────────────────────
    def save(self, weights_path: Path = WEIGHTS_PATH, meta_path: Path = META_PATH) -> None:
        if not (HAS_TORCH and self._model is not None):
            return
        weights_path.parent.mkdir(parents=True, exist_ok=True)
        torch.save(self._model.state_dict(), weights_path)
        with open(meta_path, "w") as f:
            json.dump({
                "model_version": self.model_version,
                "window_size": self.window_size,
                "features": list(self.features),
                "threshold": self.threshold,
                "mean": self.mean.tolist() if self.mean is not None else None,
                "std": self.std.tolist() if self.std is not None else None,
                "last_retrained": self.last_retrained,
                "training_samples": self.training_samples,
                "validation_precision": self.validation_precision,
            }, f, indent=2)

    def load(self, weights_path: Path = WEIGHTS_PATH, meta_path: Path = META_PATH) -> bool:
        if not HAS_TORCH:
            return False
        if not (weights_path.exists() and meta_path.exists()):
            return False
        try:
            with open(meta_path) as f:
                meta = json.load(f)
            meta_window = int(meta["window_size"])
            if meta_window != int(self.window_size):
                return False
            self.features = list(meta["features"])
            self.threshold = float(meta["threshold"])
            self.mean = np.asarray(meta["mean"], dtype=np.float32) if meta.get("mean") else None
            self.std  = np.asarray(meta["std"],  dtype=np.float32) if meta.get("std")  else None
            self.last_retrained = meta.get("last_retrained")
            self.training_samples = int(meta.get("training_samples", 0))
            self.validation_precision = float(meta.get("validation_precision", 0.0))
            self.model_version = meta.get("model_version", self.model_version)
            self._model = LeakLSTM(n_features=len(self.features))
            self._model.load_state_dict(torch.load(weights_path, map_location="cpu"))
            self._model.eval()
            self.ready = True
            return True
        except Exception as e:                            # pragma: no cover
            print(f"[leak-lstm] failed to load weights: {e}")
            return False

    # ── Training (synthetic) ────────────────────────────────────────────
    def train_synthetic(self, epochs: int = 15) -> None:
        if not HAS_TORCH:
            print("[leak-lstm] torch unavailable — running heuristic-only mode")
            self.ready = False
            return

        X, y = _synthesize_dataset(window=self.window_size)
        # split last 20% as validation
        n_val = max(64, int(len(X) * 0.2))
        Xtr, Xva = X[:-n_val], X[-n_val:]
        ytr, yva = y[:-n_val], y[-n_val:]

        mean, std = _fit_scaler(Xtr)
        Xtr_s = _scale(Xtr, mean, std)
        Xva_s = _scale(Xva, mean, std)

        device = torch.device("cpu")
        self._model = LeakLSTM(n_features=len(self.features)).to(device)
        optim = torch.optim.Adam(self._model.parameters(), lr=2e-3)
        # weighted BCE — anomalies are minority
        pos_weight = torch.tensor([float((y == 0).sum() / max((y == 1).sum(), 1))])
        loss_fn = nn.BCEWithLogitsLoss(pos_weight=pos_weight)

        ds = TensorDataset(torch.from_numpy(Xtr_s), torch.from_numpy(ytr))
        loader = DataLoader(ds, batch_size=64, shuffle=True)

        for epoch in range(epochs):
            self._model.train()
            running = 0.0
            for xb, yb in loader:
                logits = self._model(xb)
                loss = loss_fn(logits, yb)
                optim.zero_grad()
                loss.backward()
                optim.step()
                running += loss.item() * xb.size(0)
            running /= len(ds)
            if (epoch + 1) % 5 == 0:
                print(f"[leak-lstm] epoch {epoch+1:02d}/{epochs}  loss={running:.4f}")

        # Validation + threshold pick
        self._model.eval()
        with torch.no_grad():
            probs = torch.sigmoid(self._model(torch.from_numpy(Xva_s))).cpu().numpy()
        thr, prec = _pick_threshold(probs, yva, target_precision=0.7)

        self.threshold = thr
        self.mean, self.std = mean, std
        self.validation_precision = prec
        self.training_samples = int(len(X))
        self.last_retrained = datetime.now(timezone.utc).isoformat()
        self.ready = True
        self.save()
        print(f"[leak-lstm] trained — thr={thr:.3f} val_precision={prec:.3f} samples={len(X)}")

    def ensure_trained(self) -> None:
        """Load weights if present, otherwise train synthetic."""
        if not HAS_TORCH:
            return
        if not self.load():
            self.train_synthetic()

    # ── Inference ───────────────────────────────────────────────────────
    def score_window(self, window: List[List[float]]) -> float:
        """Return P(anomaly) for a complete window of `window_size` rows."""
        if not (HAS_TORCH and self.ready and self._model is not None):
            return 0.0
        arr = np.asarray(window, dtype=np.float32)
        if arr.shape != (self.window_size, len(self.features)):
            return 0.0
        if self.mean is not None and self.std is not None:
            arr = (arr - self.mean) / self.std
        with torch.no_grad():
            logit = self._model(torch.from_numpy(arr).unsqueeze(0))
            p = torch.sigmoid(logit).item()
        return float(p)

    def push_and_score(self, sensor_id: str, sample: Dict[str, float]) -> Tuple[float, str]:
        """Append a sample to the rolling buffer; return (probability, status)."""
        buf = self._buffers.setdefault(sensor_id, [])
        buf.append([float(sample.get(f, 0.0)) for f in self.features])
        if len(buf) > self.window_size:
            del buf[: len(buf) - self.window_size]

        if len(buf) < self.window_size:
            return 0.0, "warming_up"
        prob = self.score_window(buf)
        if not self.ready:
            return prob, "insufficient_data"
        return prob, "active"


# ── Singleton accessor ───────────────────────────────────────────────────

_singleton: Optional[LeakLSTMService] = None


def get_leak_lstm() -> LeakLSTMService:
    global _singleton
    if _singleton is None:
        _singleton = LeakLSTMService()
        _singleton.ensure_trained()
    return _singleton
